var context  = {
	"farning": {
		"name":                     "Farning Programmierschule",
		"website_url":              "https://www.farning.de",
		"adresse":                  "Fürstenstraße 5, 80333 München",
		"google_maps_url":          "https://maps.app.goo.gl/UbLxghaJKeeeyiFc7",
		"überthema":                ["Informatik"],
		"unterthema":               ["KI", "Programmieren", "Web-Entwicklung", "Spiele-Entwicklung", "Technische Informatik"],
		"zielgruppe":               3,
		"altersgruppe":             "8-18 Jahre",
		"teilnehmer_anzahl":        "Maximal 8",
		"schularten":               ["-"],
		"dauer":                    "999",
		"sprachen":                 "Deutsch, Englisch",
		"praktika":                 ["Schülerpraktika"],
		"w-seminare":               "-",
		"betreuungspersonal":       "Ein Informatiker pro Gruppe",
		"außerschulisches_angebot": "Ausschließlich außerschulisches Angebot",
		"beschreibung":             "Informatikinteressierte 8- bis 18-Jährige können bei Farning abseits der Schule in 60- bis 90-minütigen Kursen von bis zu 8 Personen lernen, zu programmieren. Diese Kurse drehen sich um künstliche Intelligenz, Webprogrammierung, Spielprogrammierung, vermitteln den Schülern mathematische Grundlagen und werden in Deutsch sowie Englisch gehalten. Zudem können die Schüler eigene Projekte in Gruppen selbstständig umsetzen. Interessenten können ganzjährig eine Probestunde vereinbaren. Bei beidseitigem Interesse an einer langfristigen Teilnahme wird man in der Regel erst auf eine Warteliste gesetzt, bevor man einer Gruppe beitreten kann, die zu den Vorkenntnissen des Schülers passt. Neben dem Erlangen fachlicher Kompetenzen schafft Farning sozialen Ausgleich zwischen Informatikbegeisterten.",
		"buchungsadresse":          "aufnahme@farning.de",
		"öffnungszeiten":           null,
		"images":                   ["/bilder/farning/1.jpg","/bilder/farning/2.jpg","/bilder/farning/3.jpg",
									"/bilder/farning/4.jpg","/bilder/farning/5.jpg","/bilder/farning/6.jpg","/bilder/farning/7.jpg"],
	},

	"maxlab": {
		"name":                     "Max Lab",
		"website_url":              "https://www.bi.mpg.de/maxlab",
		"adresse":                  "Am Klopferspitz 18, 82152 Planegg-Martinsried",
		"google_maps_url":          "https://maps.app.goo.gl/yiFJDpRHufFwvw8W9",
		"überthema":                ["Biologie"],
		"unterthema":               ["Molekularbiologie", "Proteinchemie", "Neurobiologie", "Ornithologie", "Biochemie", "Medizin"],
		"zielgruppe":               2,
		"dauer":                    "999"
		"altersgruppe":             "Uneingeschränkt",
		"teilnehmer_anzahl":        "Maximal 20 Personen",
		"schularten":               ["Gymnasium", "Realschule"],
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Betriebspraktika für Mittelstufenschüler einmal im Jahr",
		"w-seminare":               "Festes Kursangebot für W-Seminare",
		"betreuungspersonal":       "Leitung des MaxLabs, Studenten sowie Auszubildende",
		"außerschulisches_angebot": "Online Escape Room Spiel, Kurse in den Sommerferien, Virtuelle Schulstunden",
		"beschreibung":             "Das Angebot des Maxlabs richtet sich primär an Schülergruppen aus der Oberstufe, wobei die maximale Teilnehmeranzahl 20 Personen beträgt. Die Kurse stehen Schülern von Gymnasien und Realschulen offen und werden in deutscher Sprache durchgeführt. Das Fachgebiet der Angebote erstreckt sich über verschiedene Bereiche der Biologie, darunter Molekularbiologie, Proteinchemie, Neurobiologie, Ornithologie, Biochemie und Medizin. Die Teilnahme an den Kursen ist kostenfrei. Die Kurse haben eine Dauer von 5-6 Stunden und bieten den Teilnehmern die Möglichkeit, sich in verschiedenen Teilgebieten der Biologie zu vertiefen und praktische Erfahrungen zu sammeln. Zu einem festen Termin können Schüler einmal jährlich ein Schülerpraktikum absolvieren. Zusätzlich können Schüler online ein PCR Escape Game, in dem sie zur Abwendung einer Katastrophe Rätsel lösen müssen, absolvieren. Darüber hinaus besteht die Möglichkeit, an virtuellen Unterrichtsstunden zu den Themen 'Faszination Gehirn' und 'Vom genetischen Code zum Proteom' teilzunehmen. Die virtuellen Öffnungszeiten sind flexibel, wobei die regulären Termine mittwochs und donnerstags liegen. Diese bieten Schülern die Gelegenheit, sich in unterschiedlichen biologischen Disziplinen weiterzubilden und ihre Interessen zu vertiefen.",
		"buchungsadresse":          "ina.peters@bi.mpg.de",
		"öffnungszeiten":           null,
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"experimentier-werkstatt": {
		"name":                     "Deutsches Museum - Experimentier-Werkstatt",
		"website_url":              "https://www.deutsches-museum.de/museumsinsel/programm/programm-a-z/experimentier-werkstatt",
		"adresse":                  "Museumsinsel 1, 80538 München",
		"google_maps_url":          "https://maps.app.goo.gl/58Jdcq3m3PqZXBmk8",
		"überthema":                ["Verschiedenes"],
		"unterthema":               ["Sensorik", "Optoelektronik", "Akustik", "Elektronik", "Optik"],
		"zielgruppe":               2,
		"altersgruppe":             "Abhängig von Workshop",
		"teilnehmer_anzahl":        "Maximal 16",
		"dauer":                    "60 oder 75 Minuten",
		"schularten":               "Abhängig von Workshop",
		"sprachen":                 "Deutsch<br>Englisch (20€)<br>Französisch (20€)",
		"praktika":                 "Möglich auf Anfrage",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "Leitung, Werkstudenten",
		"außerschulisches_angebot": "Für Museumsbesucher",
		"beschreibung":             "Die Experimentier-Werkstatt im Deutschen Museum präsentiert eine umfangreiche Auswahl an Workshops für Schüler verschiedener Altersgruppen, die unterschiedliche Bereiche der MINT-Fächer abdecken. Sie steht auch Museumsbesuchern offen. Jeder Workshop kann maximal 16 Schüler aufnehmen, und die Sprachoptionen umfassen Deutsch sowie Englisch und Französisch gegen einen Aufpreis von 20€. Im 75-minütigen 'Sensor Lab' tauchen Schüler der Klassenstufen 8-12 in das Teilgebiet der Sensorik ein. Für Schüler der Klassenstufen 7-10 bietet der Workshop 'Licht mach Musik' in 75 Minuten einen Einblick in die Optoelektronik. Der 60 Minuten lange Workshop 'Hört! Hört!' fokussiert sich auf das Teilgebiet der Akustik und ist für Schüler der Klassen 4-10 zugänglich. Im Bereich Elektronik ermöglicht der 60-minütige Workshop 'Strom ab!' Schülern der Klassen 3-7 praktische Erfahrungen. Schüler der Klassenstufen 4-12 können am Workshop 'Malen mit Licht' für 60 Minuten teilnehmen, der das Teilgebiet der Optik abdeckt. Für Schüler der Klassen 6-8 steht der 75-minütige Online-Workshop 'Sensorik' zur Verfügung. Die Kosten der Workshops in Euro entsprechen der jeweiligen Workshopdauer in Minuten. Die Öffnungszeiten sind prinzipiell montags bis freitags vormittags, jedoch sind individuelle Abweichungen möglich und können durch Anfragen geklärt werden. Die Experimentier-Werkstatt verfolgt das Ziel, die Neugier für MINT-Fächer zu wecken und zu fördern. Durch verblüffende Experimente sollen Kinder und Jugendliche fasziniert werden. Das Schülerlabor trägt zur Nachwuchsförderung im MINT-Bereich bei und unterstützt die allgemeine Technik- und Wissenschaftsmündigkeit. Es ermöglicht Schülern, Technik in ihrer Umgebung besser zu verstehen und sich für Themen wie Klimawandel und Energiewende zu sensibilisieren. ",
		"buchungsadresse":          "https://www.deutsches-museum.de/museumsinsel/programm/programm-a-z/experimentier-werkstatt",
		"öffnungszeiten":           null,
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"photonlab": {
		"name":                     "Photon Lab",
		"website_url":              "https://www.mpq.mpg.de/photonlab",  /* ? oder https://www.photonworld.de/de/photonlab */
		"adresse":                  "Hans-Kopfermann-Straße 1, 85748 Garching bei München",
		"google_maps_url":          "https://maps.app.goo.gl/NDA3R8FDx5eE2UgWA",
		"überthema":                ["Optik", "Quantenoptik"],
		"unterthema":               ["Laser", "Doppelspalt", "Michelson-Interferometer"],
		"zielgruppe":               1,
		"altersgruppe":             "10.- 12. Klasse<br>Grundlegende Kenntnisse zu Physik und Licht werden vorausgesetzt.",
		"teilnehmer_anzahl":        "15",
		"dauer":                    "Vormittag",
		"schularten":               ["Gym", "FOS", "BOS"],
		"sprachen":                 "Deutsch",
		"praktika":                 "Ja",
		"w-seminare":               "Ja",
		"betreuungspersonal":       "-", /* ? */
		"außerschulisches_angebot": "Tag der offenen Türen (3.11)<br>Hilfe bei Wettbewerben (Physikolympiade)<br>Lehrerfortbildungeny<br>Campusquiz",
		"beschreibung":             "Das Ziel ist es auch Laien das Thema Licht und Laser näherzubringen, wie Laser funktionieren und wie sie aufgebaut sind. Außerdem wird das Thema Quantenphysik in Ansätzen erklärt, auf Nach-/Anfrage wird auch mehr zu dem Thema erklärt. Der Besuch beginnt mit einem Einführungsvortrag, anschließend darf man 20 spannende Experimente mit Lasern machen mit Einleitungen am IPad, zum Beispiel einen echten Doppelspalt oder Musikübertragung per Laser.  Man bekommt auch die Möglichkeit durch eine Glaswand in das Labor für Attosekundenphysik reinzugucken",
		"buchungsadresse":          "+49 89 3 29 05 - 197 Dr. Silke Stähler Schöpf, war zu dumm die Email zu entziffern https://www.mpq.mpg.de/person/34870/6533024",
		"öffnungszeiten":           "Mo-Fr 8-16 Uhr",
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"eso-supernova": {
		"name":                     "Eso Supernova",
		"website_url":              "https://supernova.eso.org/germany/",
		"adresse":                  "Karl-Schwarzschild-Straße 2, 85748 Garching bei München",
		"google_maps_url":          "https://maps.app.goo.gl/U1rw9Ak8rmkQPpph6",
		"überthema":                ["Astrophysik"],
		"unterthema":               ["Sterne", "Palneten", "Teleskope"],
		"dauer":                    "#########################################",
		"altersgruppe":             "4-18 Jahre (je nach Workshop)",
		"teilnehmer_anzahl":        "Schulklasse (Maximal 30 Schüler)",
		"zielgruppe":               2, /* ? selbst eingefügt */
		"schularten":               "alles von Grundschule bis Sekundarstufe I", /* ? Sekundarstufe I */
		"sprachen":                 "Hauptsächlich Deutsch<br>Andere Sprachen auf Anfrage (nur Planetarium und Führungen)",
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "Nein",
		"außerschulisches_angebot": "Girls-Day<br>Führungen auch im Hauptquatier/Berufsorientierung",
		"beschreibung":             "Das ESO bietet 6 Workshops an, die die Erforschung des Weltalls näherbringen sollen. Das Ziel ist die Sensibilisierung auf Naturwissenschaften, deswegen, bieten sie Workshops und Weiterildungen für Kinder und Erwachsene an. Dabei werden die Grundlagen der Optik mit alltäglichen Gegenständen erklärt und in einen astronomischen Kontext gebracht.",
		"buchungsadresse":          "https://supernova.eso.org/germany/visit/",
		"öffnungszeiten":           "Mi-Fr 9-12 & Sa,So 12-17",
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"e-conversion": {
		"name":                     "Exzellenz-Cluster e-conversion", /* ? */
		"website_url":              "https://www.e-conversion.de/school-program/",
		"adresse":                  "Lichtenbergstraße 4a, 85748 Garching ; ausweichend Boltzmannstraße 15, 85748 Garching",
		"google_maps_url":          "https://maps.app.goo.gl/QyxcuJGySfV18nNe8",
		"überthema":                ["Physik", "Chemie", "Biologie"],
		"unterthema":               ["Energieforschung", "Energieumwandlung", "Klimawandel", "Klimawandel", "erneuerbare Energien", "Batterien", "Thermodynamik", "Photosynthese"],
		"zielgruppe":               "1 (abgesehen von Feroenworkshops)",
		"altersgruppe":             "12 Jahre - Abitur, vor allem Schüler der Mittel- und Oberstufe an Gymnasien",
		"teilnehmer_anzahl":        "ca 15, max 25",
		"dauer":                    "abhängig vom Workshop, meistens mehrere Vormittage",
		"schularten":               "Vor allem Gymnasium, auch Real- oder Mittelschule",
		"sprachen":                 "Deutsch, Englisch",
		"praktika":                 "Nein (zumindest nicht beim Schülerlabor)",
		"w-seminare":               "Nur auf Anfrage",
		"betreuungspersonal":       "Leitung, Doktoranden, Postdocs",
		"außerschulisches_angebot": "variiert, aktuelle Infos auf Website",
		"beschreibung":             "Das Exzellenz-Cluster e-conversion richtet sich an Schulklassen, die in Garching einen Workshop machen wollen, um den Blick zu erweitern, für MINT Fächer zu begeistern und die Art und Weise wissenschaftlicher Forschung zu sehen.",
		"buchungsadresse":          "silke.mayerl@e-conversion.de",
		"öffnungszeiten":           "werktags vormittags",
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"ix-quadrat": {
		"name":                     "ix-quadrat",
		"website_url":              "https://www.ma.tum.de/de/schulportal/ix-quadrat.html",
		"adresse":                  "Boltzmannstraße 3, 85748 Garching",
		"google_maps_url":          "https://maps.app.goo.gl/ZoaVEZ9SdieEXwZcA",
		"überthema":                ["Mathematik"],
		"unterthema":               ["Symmetrie"],
		"zielgruppe":               1,
		"altersgruppe":             "Uneingeschränkt",
		"teilnehmer_anzahl":        "Maximal 30",
		"dauer":                    "2 Stunden",
		"schularten":               "Uneingeschränkt",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "-",
		"außerschulisches_angebot": "Besuch Einzelpersonen",
		"beschreibung":             "Die Mitmach-Ausstellung ix-quadrat öffnet die faszinierende Welt der Mathematik für Menschen jeden Alters und unabhängig von ihrem Vorwissen. Hier wird Mathematik erlebbar und begreifbar gemacht. Für Schulklassen bis zu 30 Personen wird die Möglichkeit geboten, sich für einen etwa 2-stündigen Besuch anzumelden. Schüler können in die interaktiven Ausstellungsbereiche eintauchen, Symmetrie entdecken, in die Welt der Zahlen greifen und die Perspektiven des Grafikers und Künstlers M. C. Escher erforschen. Einzelpersonen können zu den Öffnungszeiten die Ausstellung unangemeldet besuchen.",
		"buchungsadresse":          "ix-quadrat@ma.tum.de ",
		"öffnungszeiten":           "Eigenen Website",
		"images":                   [],
	},

	"SWM Bildungsangebote": {
		"name":                     "SWM Bildungsangebote", // Von aktueller website übernommen
		"website_url":              "https://www.swm.de/schule/besichtigungen-veranstaltungen",
		"adresse":                  "Emmy-Noether-Straße 2, 80992 München", // Da es verschidenen Standorte gitb ist das die Adresse vom "SWM Service für schulen"
		"google_maps_url":          "https://maps.app.goo.gl/GZuET8MmjMwvQMq57", // Das gleiche hier
		"überthema":                ["Physik"],
		"unterthema":               ["Energie-/Trinkwassergewinnung, Öffentlicher Verkehr"],
		"zielgruppe":               1,
		"altersgruppe":             "Schüler",
		"teilnehmer_anzahl":        "Eine Schulklasse bis 50 je nach Workshop",
		"dauer":                    "################################", // Keine Ahnung was hier reinkommt
		"schularten":               "Uneingeschränkt",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "-",
		"außerschulisches_angebot": "-",
		"beschreibung":             "Die SWM Bildungsangebote erstrecken sich über eine Vielfalt an Themenbereichen, von Energiegewinnung über Trinkwassergewinnung, bis hin zu der Funktion der öffentlichen Verkehrsmitteln in München. Es besteht die Möglichekeit, Energiekraftwerke zu besuchen, oder Kurse zum richtigen Busfahren zu buchen.",
		"buchungsadresse":          "Per Formular auf der Website: https://www.swm.de/schule/besichtigungen-veranstaltungen/anmeldung-neu oder terilweise schulkontakt@swm.de",
		"öffnungszeiten":           "Variabel",
		"images":                   [],
	},

	"FabLab": {
		"name":                     "FabLab",
		"website_url":              "https://www.fablab-muenchen.de/",
		"adresse":                  "Gollierstraße 70, 80339 München",
		"google_maps_url":          "https://maps.app.goo.gl/GsbSmNG6R4BEgCJ26",
		"überthema":                ["Handwerk"],
		"unterthema":               ["Handwerk"],
		"zielgruppe":               2,
		"altersgruppe":             "Uneingeschränkt",
		"teilnehmer_anzahl":        "Eine Klasse",
		"dauer":                    "#############################", // Keine Ahnung was hier reinkommt
		"schularten":               "Uneingeschränkt",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Ja",
		"w-seminare":               "Jaein",
		"betreuungspersonal":       "-",
		"außerschulisches_angebot": "Selbstständiges Nutzen der Werkstatt möglich",
		"beschreibung":             "Das FabLab ist eine Werkstatt, die auch für Schulklassen einführungen in das Handwerkliche Arbeiten anbietet. Neben den schon angesprochenen Workshops für Schulen besteht auch die Möglichkeit gegen einen Mitgliedsbeitrag die umfangreich ausgestatte Werkstatt auch alleine zu nutzen.",
		"buchungsadresse":          "birgit@fablab-muenchen.de",
		"öffnungszeiten":           "Schullab Montag & Freitag Vormittag, Werkstatt immer",
		"images":                   [],
	},

	"Genetik macht Schule": {
		"name":                     "Genetik macht Schule",
		"website_url":              "https://teaching.genetik.biologie.uni-muenchen.de/teaching/kurse/genetik-macht-schule",
		"adresse":                  "Großhaderner Str. 2, 82152 Planegg",
		"google_maps_url":          "https://maps.app.goo.gl/r1jxcKn3LaJoZMKw5",
		"überthema":                ["Biologie"],
		"unterthema":               ["Genetik"],
		"zielgruppe":               1,
		"altersgruppe":             "Oberstufe",
		"teilnehmer_anzahl":        "maximal 24",
		"dauer":                    "################################", // Keine Ahnung was hier reinkommt
		"schularten":               "Gymnasium",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "Studierende",
		"außerschulisches_angebot": "-",
		"beschreibung":             "Genetik macht Schule vereint die Interessen von Schülern und Studierenden, - erstere kriegen eine spannede Unterichtsstunde mit anschliessendem praktischen Teil, letztere hingegen können Erfahrungen im Schüler unterichten sammeln. Die dem prakzischen Teil vorangehende Unterichsstunde wird von einem Studierenden vor, auf welches eine Woche später ein Experiment folgt welches das gelernte nochmal festigt.",
		"buchungsadresse":          "brachman@lmu.de",
		"öffnungszeiten":           "Siehe Website",
		"images":                   [],
	},

	/*
	  Die Attribute in diesem Muster dienen der Überprüfung der Datenvollständigkeit bei allen anderen Labs.
	  Bitte möglichst beibehalten und wenn nötig übergreifend ändern.
	*/
	"Muster": {
		"name":                     "",
		"website_url":              "",
		"adresse":                  "",
		"google_maps_url":          "",
		"überthema":                [""],
		"unterthema":               [""],
		"zielgruppe":               0,
		"altersgruppe":             "",
		"teilnehmer_anzahl":        "",
		"dauer":                    "",
		"schularten":               [""],
		"sprachen":                 [""],
		"praktika":                 [""],
		"w-seminare":               "",
		"betreuungspersonal":       "",
		"außerschulisches_angebot": "",
		"beschreibung":             "",
		"buchungsadresse":          "",
		"öffnungszeiten":           null,
		"images":                   [],
	},
};

interal_to_displayed_mapping= {
	"zielgruppe":               "Zielgruppe",
	"altersgruppe":             "Altersgruppe",
	"teilnehmer_anzahl":        "Teilnehmeranzahl",
	"schularten":               "Schularten",
	"sprachen":                 "Sprachen",
	"praktika":                 "Praktika",
	"w-seminare":               "W-Seminare",
	"betreuungspersonal":       "Betreuungspersonal",
	"außerschulisches_angebot": "Außerschulisches Angebot",
}

tags_to_color_mapping = {
	"Informatik": "grey",
	"Mathematik": "blue",
	"Biologie":   "green",
	"Chemie":     "yellow",
};
