var context  = {
	"farning": {
		"name":                     "Farning Programmierschule",
		"website_url":              "https://www.farning.de",
		"adresse":                  "FÃ¼rstenstraÃŸe 5, 80333 MÃ¼nchen",
		"google_maps_url":          "https://maps.app.goo.gl/UbLxghaJKeeeyiFc7",
		"Ã¼berthema":                ["Informatik"],
		"unterthema":               ["KI", "Programmieren", "Web-Entwicklung", "Spiele-Entwicklung", "Technische Informatik"],
		"zielgruppe":               3,
		"altersgruppe":             "8-18 Jahre",
		"teilnehmer_anzahl":        "Maximal 8",
		"schularten":               ["-"],
		"sprachen":                 "Deutsch, Englisch",
		"praktika":                 ["SchÃ¼lerpraktika"],
		"w-seminare":               "-",
		"betreuungspersonal":       "Ein Informatiker pro Gruppe",
		"auÃŸerschulisches_angebot": "AusschlieÃŸlich auÃŸerschulisches Angebot",
		"beschreibung":             "Informatikinteressierte 8- bis 18-JÃ¤hrige kÃ¶nnen bei Farning abseits der Schule in 60- bis 90-minÃ¼tigen Kursen von bis zu 8 Personen lernen, zu programmieren. Diese Kurse drehen sich um kÃ¼nstliche Intelligenz, Webprogrammierung, Spielprogrammierung, vermitteln den SchÃ¼lern mathematische Grundlagen und werden in Deutsch sowie Englisch gehalten. Zudem kÃ¶nnen die SchÃ¼ler eigene Projekte in Gruppen selbststÃ¤ndig umsetzen. Interessenten kÃ¶nnen ganzjÃ¤hrig eine Probestunde vereinbaren. Bei beidseitigem Interesse an einer langfristigen Teilnahme wird man in der Regel erst auf eine Warteliste gesetzt, bevor man einer Gruppe beitreten kann, die zu den Vorkenntnissen des SchÃ¼lers passt. Neben dem Erlangen fachlicher Kompetenzen schafft Farning sozialen Ausgleich zwischen Informatikbegeisterten.",
		"buchungsadresse":          "aufnahme@farning.de",
		"Ã¶ffnungszeiten":           null,
		"images":                   ["/bilder/farning/1.jpg","/bilder/farning/2.jpg","/bilder/farning/3.jpg",
									"/bilder/farning/4.jpg","/bilder/farning/5.jpg","/bilder/farning/6.jpg","/bilder/farning/7.jpg"],
	},

	"maxlab": {
		"name":                     "Max Lab",
		"website_url":              "https://www.bi.mpg.de/maxlab",
		"adresse":                  "Am Klopferspitz 18, 82152 Planegg-Martinsried",
		"google_maps_url":          "https://maps.app.goo.gl/yiFJDpRHufFwvw8W9",
		"Ã¼berthema":                ["Biologie"],
		"unterthema":               ["Molekularbiologie", "Proteinchemie", "Neurobiologie", "Ornithologie", "Biochemie", "Medizin"],
		"zielgruppe":               2,
		"altersgruppe":             "UneingeschrÃ¤nkt",
		"teilnehmer_anzahl":        "Maximal 20 Personen",
		"schularten":               ["Gymnasium", "Realschule"],
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Betriebspraktika fÃ¼r MittelstufenschÃ¼ler einmal im Jahr",
		"w-seminare":               "Festes Kursangebot fÃ¼r W-Seminare",
		"betreuungspersonal":       "Leitung des MaxLabs, Studenten sowie Auszubildende",
		"auÃŸerschulisches_angebot": "Online Escape Room Spiel, Kurse in den Sommerferien, Virtuelle Schulstunden",
		"beschreibung":             "Das Angebot des Maxlabs richtet sich primÃ¤r an SchÃ¼lergruppen aus der Oberstufe, wobei die maximale Teilnehmeranzahl 20 Personen betrÃ¤gt. Die Kurse stehen SchÃ¼lern von Gymnasien und Realschulen offen und werden in deutscher Sprache durchgefÃ¼hrt. Das Fachgebiet der Angebote erstreckt sich Ã¼ber verschiedene Bereiche der Biologie, darunter Molekularbiologie, Proteinchemie, Neurobiologie, Ornithologie, Biochemie und Medizin. Die Teilnahme an den Kursen ist kostenfrei. Die Kurse haben eine Dauer von 5-6 Stunden und bieten den Teilnehmern die MÃ¶glichkeit, sich in verschiedenen Teilgebieten der Biologie zu vertiefen und praktische Erfahrungen zu sammeln. Zu einem festen Termin kÃ¶nnen SchÃ¼ler einmal jÃ¤hrlich ein SchÃ¼lerpraktikum absolvieren. ZusÃ¤tzlich kÃ¶nnen SchÃ¼ler online ein PCR Escape Game, in dem sie zur Abwendung einer Katastrophe RÃ¤tsel lÃ¶sen mÃ¼ssen, absolvieren. DarÃ¼ber hinaus besteht die MÃ¶glichkeit, an virtuellen Unterrichtsstunden zu den Themen 'Faszination Gehirn' und 'Vom genetischen Code zum Proteom' teilzunehmen. Die virtuellen Ã–ffnungszeiten sind flexibel, wobei die regulÃ¤ren Termine mittwochs und donnerstags liegen. Diese bieten SchÃ¼lern die Gelegenheit, sich in unterschiedlichen biologischen Disziplinen weiterzubilden und ihre Interessen zu vertiefen.",
		"buchungsadresse":          "ina.peters@bi.mpg.de",
		"Ã¶ffnungszeiten":           null,
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"experimentier-werkstatt": {
		"name":                     "Deutsches Museum - Experimentier-Werkstatt",
		"website_url":              "https://www.deutsches-museum.de/museumsinsel/programm/programm-a-z/experimentier-werkstatt",
		"adresse":                  "Museumsinsel 1, 80538 MÃ¼nchen",
		"google_maps_url":          "https://maps.app.goo.gl/58Jdcq3m3PqZXBmk8",
		"Ã¼berthema":                ["Verschiedenes"],
		"unterthema":               ["Sensorik", "Optoelektronik", "Akustik", "Elektronik", "Optik"],
		"zielgruppe":               2,
		"altersgruppe":             "AbhÃ¤ngig von Workshop",
		"teilnehmer_anzahl":        "Maximal 16",
		"dauer":                    "60 oder 75 Minuten",
		"schularten":               "AbhÃ¤ngig von Workshop",
		"sprachen":                 "Deutsch<br>Englisch (20â‚¬)<br>FranzÃ¶sisch (20â‚¬)",
		"praktika":                 "MÃ¶glich auf Anfrage",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "Leitung, Werkstudenten",
		"auÃŸerschulisches_angebot": "FÃ¼r Museumsbesucher",
		"beschreibung":             "Die Experimentier-Werkstatt im Deutschen Museum prÃ¤sentiert eine umfangreiche Auswahl an Workshops fÃ¼r SchÃ¼ler verschiedener Altersgruppen, die unterschiedliche Bereiche der MINT-FÃ¤cher abdecken. Sie steht auch Museumsbesuchern offen. Jeder Workshop kann maximal 16 SchÃ¼ler aufnehmen, und die Sprachoptionen umfassen Deutsch sowie Englisch und FranzÃ¶sisch gegen einen Aufpreis von 20â‚¬. Im 75-minÃ¼tigen 'Sensor Lab' tauchen SchÃ¼ler der Klassenstufen 8-12 in das Teilgebiet der Sensorik ein. FÃ¼r SchÃ¼ler der Klassenstufen 7-10 bietet der Workshop 'Licht mach Musik' in 75 Minuten einen Einblick in die Optoelektronik. Der 60 Minuten lange Workshop 'HÃ¶rt! HÃ¶rt!' fokussiert sich auf das Teilgebiet der Akustik und ist fÃ¼r SchÃ¼ler der Klassen 4-10 zugÃ¤nglich. Im Bereich Elektronik ermÃ¶glicht der 60-minÃ¼tige Workshop 'Strom ab!' SchÃ¼lern der Klassen 3-7 praktische Erfahrungen. SchÃ¼ler der Klassenstufen 4-12 kÃ¶nnen am Workshop 'Malen mit Licht' fÃ¼r 60 Minuten teilnehmen, der das Teilgebiet der Optik abdeckt. FÃ¼r SchÃ¼ler der Klassen 6-8 steht der 75-minÃ¼tige Online-Workshop 'Sensorik' zur VerfÃ¼gung. Die Kosten der Workshops in Euro entsprechen der jeweiligen Workshopdauer in Minuten. Die Ã–ffnungszeiten sind prinzipiell montags bis freitags vormittags, jedoch sind individuelle Abweichungen mÃ¶glich und kÃ¶nnen durch Anfragen geklÃ¤rt werden. Die Experimentier-Werkstatt verfolgt das Ziel, die Neugier fÃ¼r MINT-FÃ¤cher zu wecken und zu fÃ¶rdern. Durch verblÃ¼ffende Experimente sollen Kinder und Jugendliche fasziniert werden. Das SchÃ¼lerlabor trÃ¤gt zur NachwuchsfÃ¶rderung im MINT-Bereich bei und unterstÃ¼tzt die allgemeine Technik- und WissenschaftsmÃ¼ndigkeit. Es ermÃ¶glicht SchÃ¼lern, Technik in ihrer Umgebung besser zu verstehen und sich fÃ¼r Themen wie Klimawandel und Energiewende zu sensibilisieren. ",
		"buchungsadresse":          "https://www.deutsches-museum.de/museumsinsel/programm/programm-a-z/experimentier-werkstatt",
		"Ã¶ffnungszeiten":           null,
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"photonlab": {
		"name":                     "Photon Lab",
		"website_url":              "https://www.mpq.mpg.de/photonlab",  /* ? oder https://www.photonworld.de/de/photonlab */
		"adresse":                  "Hans-Kopfermann-StraÃŸe 1, 85748 Garching bei MÃ¼nchen",
		"google_maps_url":          "https://maps.app.goo.gl/NDA3R8FDx5eE2UgWA",
		"Ã¼berthema":                ["Optik", "Quantenoptik"],
		"unterthema":               ["Laser", "Doppelspalt", "Michelson-Interferometer"],
		"zielgruppe":               1,
		"altersgruppe":             "10.- 12. Klasse<br>Grundlegende Kenntnisse zu Physik und Licht werden vorausgesetzt.",
		"teilnehmer_anzahl":        "15",
		"dauer":                    "Vormittag",
		"schularten":               ["Gym", "FOS", "BOS"],
		"sprachen":                 "Deutsch",
		"praktika":                 "Ja",
		"w-seminare":               "Ja",
		"betreuungspersonal":       "-", /* ? */
		"auÃŸerschulisches_angebot": "Tag der offenen TÃ¼ren (3.11)<br>Hilfe bei Wettbewerben (Physikolympiade)<br>Lehrerfortbildungeny<br>Campusquiz",
		"beschreibung":             "Das Ziel ist es auch Laien das Thema Licht und Laser nÃ¤herzubringen, wie Laser funktionieren und wie sie aufgebaut sind. AuÃŸerdem wird das Thema Quantenphysik in AnsÃ¤tzen erklÃ¤rt, auf Nach-/Anfrage wird auch mehr zu dem Thema erklÃ¤rt. Der Besuch beginnt mit einem EinfÃ¼hrungsvortrag, anschlieÃŸend darf man 20 spannende Experimente mit Lasern machen mit Einleitungen am IPad, zum Beispiel einen echten Doppelspalt oder MusikÃ¼bertragung per Laser.  Man bekommt auch die MÃ¶glichkeit durch eine Glaswand in das Labor fÃ¼r Attosekundenphysik reinzugucken",
		"buchungsadresse":          "+49 89 3 29 05 - 197 Dr. Silke StÃ¤hler SchÃ¶pf, war zu dumm die Email zu entziffern https://www.mpq.mpg.de/person/34870/6533024",
		"Ã¶ffnungszeiten":           "Mo-Fr 8-16 Uhr",
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"eso-supernova": {
		"name":                     "Eso Supernova",
		"website_url":              "https://supernova.eso.org/germany/",
		"adresse":                  "Karl-Schwarzschild-StraÃŸe 2, 85748 Garching bei MÃ¼nchen",
		"google_maps_url":          "https://maps.app.goo.gl/U1rw9Ak8rmkQPpph6",
		"Ã¼berthema":                ["Astrophysik"],
		"unterthema":               ["Sterne", "Palneten", "Teleskope"],
		"dauer":                    "#########################################",
		"altersgruppe":             "4-18 Jahre (je nach Workshop)",
		"teilnehmer_anzahl":        "Schulklasse (Maximal 30 SchÃ¼ler)",
		"zielgruppe":               2, /* ? selbst eingefÃ¼gt */
		"schularten":               "alles von Grundschule bis Sekundarstufe I", /* ? Sekundarstufe I */
		"sprachen":                 "HauptsÃ¤chlich Deutsch<br>Andere Sprachen auf Anfrage (nur Planetarium und FÃ¼hrungen)",
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "Nein",
		"auÃŸerschulisches_angebot": "Girls-Day<br>FÃ¼hrungen auch im Hauptquatier/Berufsorientierung",
		"beschreibung":             "Das ESO bietet 6 Workshops an, die die Erforschung des Weltalls nÃ¤herbringen sollen. Das Ziel ist die Sensibilisierung auf Naturwissenschaften, deswegen, bieten sie Workshops und Weiterildungen fÃ¼r Kinder und Erwachsene an. Dabei werden die Grundlagen der Optik mit alltÃ¤glichen GegenstÃ¤nden erklÃ¤rt und in einen astronomischen Kontext gebracht.",
		"buchungsadresse":          "https://supernova.eso.org/germany/visit/",
		"Ã¶ffnungszeiten":           "Mi-Fr 9-12 & Sa,So 12-17",
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"e-conversion": {
		"name":                     "Exzellenz-Cluster e-conversion", /* ? */
		"website_url":              "https://www.e-conversion.de/school-program/",
		"adresse":                  "LichtenbergstraÃŸe 4a, 85748 Garching ; ausweichend BoltzmannstraÃŸe 15, 85748 Garching",
		"google_maps_url":          "https://maps.app.goo.gl/QyxcuJGySfV18nNe8",
		"Ã¼berthema":                ["Physik", "Chemie", "Biologie"],
		"unterthema":               ["Energieforschung", "Energieumwandlung", "Klimawandel", "Klimawandel", "erneuerbare Energien", "Batterien", "Thermodynamik", "Photosynthese"],
		"zielgruppe":               "1 (abgesehen von Feroenworkshops)",
		"altersgruppe":             "12 Jahre - Abitur, vor allem SchÃ¼ler der Mittel- und Oberstufe an Gymnasien",
		"teilnehmer_anzahl":        "ca 15, max 25",
		"dauer":                    "abhÃ¤ngig vom Workshop, meistens mehrere Vormittage",
		"schularten":               "Vor allem Gymnasium, auch Real- oder Mittelschule",
		"sprachen":                 "Deutsch, Englisch",
		"praktika":                 "Nein (zumindest nicht beim SchÃ¼lerlabor)",
		"w-seminare":               "Nur auf Anfrage",
		"betreuungspersonal":       "Leitung, Doktoranden, Postdocs",
		"auÃŸerschulisches_angebot": "variiert, aktuelle Infos auf Website",
		"beschreibung":             "Das Exzellenz-Cluster e-conversion richtet sich an Schulklassen, die in Garching einen Workshop machen wollen, um den Blick zu erweitern, fÃ¼r MINT FÃ¤cher zu begeistern und die Art und Weise wissenschaftlicher Forschung zu sehen.",
		"buchungsadresse":          "silke.mayerl@e-conversion.de",
		"Ã¶ffnungszeiten":           "werktags vormittags",
		"images":                   ["/bilder/welpe1.jpg","/bilder/welpe2.jpg","/bilder/welpe3.jpg"],
	},

	"ix-quadrat": {
		"name":                     "ix-quadrat",
		"website_url":              "https://www.ma.tum.de/de/schulportal/ix-quadrat.html",
		"adresse":                  "BoltzmannstraÃŸe 3, 85748 Garching",
		"google_maps_url":          "https://maps.app.goo.gl/ZoaVEZ9SdieEXwZcA",
		"Ã¼berthema":                ["Mathematik"],
		"unterthema":               ["Symmetrie"],
		"zielgruppe":               1,
		"altersgruppe":             "UneingeschrÃ¤nkt",
		"teilnehmer_anzahl":        "Maximal 30",
		"dauer":                    "2 Stunden",
		"schularten":               "UneingeschrÃ¤nkt",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "-",
		"auÃŸerschulisches_angebot": "Besuch Einzelpersonen",
		"beschreibung":             "Die Mitmach-Ausstellung ix-quadrat Ã¶ffnet die faszinierende Welt der Mathematik fÃ¼r Menschen jeden Alters und unabhÃ¤ngig von ihrem Vorwissen. Hier wird Mathematik erlebbar und begreifbar gemacht. FÃ¼r Schulklassen bis zu 30 Personen wird die MÃ¶glichkeit geboten, sich fÃ¼r einen etwa 2-stÃ¼ndigen Besuch anzumelden. SchÃ¼ler kÃ¶nnen in die interaktiven Ausstellungsbereiche eintauchen, Symmetrie entdecken, in die Welt der Zahlen greifen und die Perspektiven des Grafikers und KÃ¼nstlers M. C. Escher erforschen. Einzelpersonen kÃ¶nnen zu den Ã–ffnungszeiten die Ausstellung unangemeldet besuchen.",
		"buchungsadresse":          "ix-quadrat@ma.tum.de ",
		"Ã¶ffnungszeiten":           "Eigenen Website",
		"images":                   [],
	},

	"SWM Bildungsangebote": {
		"name":                     "SWM Bildungsangebote", // Von aktueller website Ã¼bernommen
		"website_url":              "https://www.swm.de/schule/besichtigungen-veranstaltungen",
		"adresse":                  "Emmy-Noether-StraÃŸe 2, 80992 MÃ¼nchen", // Da es verschidenen Standorte gitb ist das die Adresse vom "SWM Service fÃ¼r schulen"
		"google_maps_url":          "https://maps.app.goo.gl/GZuET8MmjMwvQMq57", // Das gleiche hier
		"Ã¼berthema":                ["Physik"],
		"unterthema":               ["Energie-/Trinkwassergewinnung, Ã–ffentlicher Verkehr"],
		"zielgruppe":               1,
		"altersgruppe":             "SchÃ¼ler",
		"teilnehmer_anzahl":        "Eine Schulklasse bis 50 je nach Workshop",
		"dauer":                    "################################", // Keine Ahnung was hier reinkommt
		"schularten":               "UneingeschrÃ¤nkt",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "-",
		"auÃŸerschulisches_angebot": "-",
		"beschreibung":             "Die SWM Bildungsangebote erstrecken sich Ã¼ber eine Vielfalt an Themenbereichen, von Energiegewinnung Ã¼ber Trinkwassergewinnung, bis hin zu der Funktion der Ã¶ffentlichen Verkehrsmitteln in MÃ¼nchen. Es besteht die MÃ¶glichekeit, Energiekraftwerke zu besuchen, oder Kurse zum richtigen Busfahren zu buchen.",
		"buchungsadresse":          "Per Formular auf der Website: https://www.swm.de/schule/besichtigungen-veranstaltungen/anmeldung-neu oder terilweise schulkontakt@swm.de",
		"Ã¶ffnungszeiten":           "Variabel",
		"images":                   [],
	},

	"FabLab": {
		"name":                     "FabLab",
		"website_url":              "https://www.fablab-muenchen.de/",
		"adresse":                  "GollierstraÃŸe 70, 80339 MÃ¼nchen",
		"google_maps_url":          "https://maps.app.goo.gl/GsbSmNG6R4BEgCJ26",
		"Ã¼berthema":                ["Handwerk"],
		"unterthema":               ["Handwerk"],
		"zielgruppe":               2,
		"altersgruppe":             "UneingeschrÃ¤nkt",
		"teilnehmer_anzahl":        "Eine Klasse",
		"dauer":                    "#############################", // Keine Ahnung was hier reinkommt
		"schularten":               "UneingeschrÃ¤nkt",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Ja",
		"w-seminare":               "Jaein",
		"betreuungspersonal":       "-",
		"auÃŸerschulisches_angebot": "SelbststÃ¤ndiges Nutzen der Werkstatt mÃ¶glich",
		"beschreibung":             "Das FabLab ist eine Werkstatt, die auch fÃ¼r Schulklassen einfÃ¼hrungen in das Handwerkliche Arbeiten anbietet. Neben den schon angesprochenen Workshops fÃ¼r Schulen besteht auch die MÃ¶glichkeit gegen einen Mitgliedsbeitrag die umfangreich ausgestatte Werkstatt auch alleine zu nutzen.",
		"buchungsadresse":          "birgit@fablab-muenchen.de",
		"Ã¶ffnungszeiten":           "Schullab Montag & Freitag Vormittag, Werkstatt immer",
		"images":                   [],
	},

	"Genetik macht Schule": {
		"name":                     "Genetik macht Schule",
		"website_url":              "https://teaching.genetik.biologie.uni-muenchen.de/teaching/kurse/genetik-macht-schule",
		"adresse":                  "GroÃŸhaderner Str. 2, 82152 Planegg",
		"google_maps_url":          "https://maps.app.goo.gl/r1jxcKn3LaJoZMKw5",
		"Ã¼berthema":                ["Biologie"],
		"unterthema":               ["Genetik"],
		"zielgruppe":               1,
		"altersgruppe":             "Oberstufe",
		"teilnehmer_anzahl":        "maximal 24",
		"dauer":                    "################################", // Keine Ahnung was hier reinkommt
		"schularten":               "Gymnasium",
		"sprachen":                 ["Deutsch"],
		"praktika":                 "Nein",
		"w-seminare":               "Nein",
		"betreuungspersonal":       "Studierende",
		"auÃŸerschulisches_angebot": "-",
		"beschreibung":             "Genetik macht Schule vereint die Interessen von SchÃ¼lern und Studierenden, - erstere kriegen eine spannede Unterichtsstunde mit anschliessendem praktischen Teil, letztere hingegen kÃ¶nnen Erfahrungen im SchÃ¼ler unterichten sammeln. Die dem prakzischen Teil vorangehende Unterichsstunde wird von einem Studierenden vor, auf welches eine Woche spÃ¤ter ein Experiment folgt welches das gelernte nochmal festigt.",
		"buchungsadresse":          "brachman@lmu.de",
		"Ã¶ffnungszeiten":           "Siehe Website",
		"images":                   [],
	},

	/*
	  Die Attribute in diesem Muster dienen der ÃœberprÃ¼fung der DatenvollstÃ¤ndigkeit bei allen anderen Labs.
	  Bitte mÃ¶glichst beibehalten und wenn nÃ¶tig Ã¼bergreifend Ã¤ndern.
	*/
	"Muster": {
		"name":                     "",
		"website_url":              "",
		"adresse":                  "",
		"google_maps_url":          "",
		"Ã¼berthema":                [""],
		"unterthema":               [""],
		"zielgruppe":               0,
		"altersgruppe":             "",
		"teilnehmer_anzahl":        "",
		"dauer":                    "",
		"schularten":               [""],
		"sprachen":                 [""],
		"praktika":                 [""],
		"w-seminare":               "",
		"betreuungspersonal":       "",
		"auÃŸerschulisches_angebot": "",
		"beschreibung":             "",
		"buchungsadresse":          "",
		"Ã¶ffnungszeiten":           null,
		"images":                   [],
	},
};

interal_to_displayed_mapping= {
	"zielgruppe":               "Zielgruppe",
	"altersgruppe":             "Altersgruppe",
	"teilnehmer_anzahl":        "Teilnehmeranzahl",
	"schularten":               "Schularten",
	"sprachen":                 "Sprachen",
	"praktika":                 "Praktika",
	"w-seminare":               "W-Seminare",
	"betreuungspersonal":       "Betreuungspersonal",
	"auÃŸerschulisches_angebot": "AuÃŸerschulisches Angebot",
}

tags_to_color_mapping = {
	"Informatik": "grey",
	"Mathematik": "blue",
	"Biologie":   "green",
	"Chemie":     "yellow",
};
